global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'celery_worker'
    static_configs:
      - targets: ['celery_worker:5555']
